apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: svc-event-messaging-ingress
spec:
  podSelector:
    matchLabels:
      app: svc-event-messaging
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: api-gateway
      ports:
        - protocol: TCP
          port: 8091