apiVersion: apps/v1
kind: Deployment
metadata:
  name: svc-alert-management
spec:
  replicas: 2
  selector:
    matchLabels:
      app: svc-alert-management
  template:
    metadata:
      labels:
        app: svc-alert-management
    spec:
      containers:
        - name: svc-alert-management
          image: ghcr.io/uttambhatia/healthcarepatientengagement/svc-alert-management:latest
          ports:
            - containerPort: 8089
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: aks
            - name: SERVICEBUS_NAMESPACE
              valueFrom:
                secretKeyRef:
                  name: platform-secrets
                  key: servicebus-namespace
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8089
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8089
