apiVersion: v1
kind: Secret
metadata:
  name: platform-secrets
  namespace: healthcare-prod-dr
type: Opaque
stringData:
  servicebus-namespace: "<secondary-servicebus-namespace>.servicebus.windows.net"
  servicebus-connection-string: "Endpoint=sb://<secondary-servicebus-namespace>.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=<secondary-servicebus-shared-access-key>"
  eventhub-namespace: "<secondary-eventhub-namespace>.servicebus.windows.net"
  key-vault-url: "https://<secondary-key-vault-name>.vault.azure.net/"
  fhir-integration-base-url: "https://<secondary-fhir-workspace>.fhir.azurehealthcareapis.com"
  service-bus-integration-base-url: "https://svc-event-messaging.healthcare-prod-dr.svc.cluster.local"
  acs-integration-base-url: "http://svc-identity-adapter"
  teleconsult-acs-integration-base-url: "http://svc-identity-adapter"
  teleconsult-join-base-url: "https://<secondary-teleconsult-public-host>/session"
  acs-identity-connection-string: "endpoint=https://<secondary-acs-resource>.communication.azure.com/;accesskey=<secondary-acs-access-key>"
  otel-otlp-endpoint: "http://otel-collector.monitoring.svc.cluster.local:4317"
  oauth2-issuer: "https://login.microsoftonline.com/<tenant-id>/v2.0"
  oauth2-audience: "api://<api-app-id-uri>"
  oauth2-jwk-set-uri: "https://login.microsoftonline.com/<tenant-id>/discovery/v2.0/keys"
  azure-blob-connection-string: "DefaultEndpointsProtocol=https;AccountName=<secondary-storage-account>;AccountKey=<secondary-storage-account-key>;EndpointSuffix=core.windows.net"
  patient-idproof-container: "patient-id-proofs"
  profile-photo-container: "user-profile-photos"
  entra-api-app-id: "<api-app-id>"
  entra-graph-base-url: "https://graph.microsoft.com/v1.0"
  entra-patient-group-name: "HCPE-PATIENT"
  entra-patient-role-value: "PATIENT"
  entra-invite-redirect-url: "https://myapplications.microsoft.com"
  azure-sql-jdbc-url: "jdbc:sqlserver://<secondary-sql-server>.database.windows.net:1433;database=<secondary-shared-db>;encrypt=true;hostNameInCertificate=*.database.windows.net;loginTimeout=30;"
  azure-sql-username: "<secondary-sql-user>"
  azure-sql-password: "<secondary-sql-password-or-token>"
  azure-managed-identity-client-id: "<secondary-user-assigned-managed-identity-client-id>"
