apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: svc-telemetry-ingress
spec:
  podSelector:
    matchLabels:
      app: svc-telemetry
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: api-gateway
      ports:
        - protocol: TCP
          port: 8087
