apiVersion: v1
kind: Secret
metadata:
  name: platform-secrets
  namespace: healthcare-dev
type: Opaque
stringData:
  servicebus-namespace: "hpe-dev-sb.servicebus.windows.net"
  eventhub-namespace: "hpe-dev-eh.servicebus.windows.net"
  key-vault-url: "https://hpe-dev-kv.vault.azure.net/"
  fhir-integration-base-url: "https://hpe-dev-fhir.azurehealthcareapis.com"
  service-bus-integration-base-url: "https://svc-event-messaging.healthcare-dev.svc.cluster.local"
  acs-integration-base-url: "http://svc-identity-adapter"
  teleconsult-acs-integration-base-url: "http://svc-identity-adapter"
  teleconsult-join-base-url: "https://<dev-teleconsult-public-host>/session"
  acs-email-endpoint: "https://<dev-acs-email-resource>.communication.azure.com"
  acs-email-access-key: "<dev-acs-email-access-key>"
  acs-email-from-address: "donotreply@<dev-acs-email-domain>"
  acs-sms-endpoint: "https://<dev-acs-resource>.communication.azure.com"
  acs-sms-access-key: "<dev-acs-sms-access-key>"
  acs-sms-from-number: "+1<dev-acs-sms-number>"
  acs-identity-connection-string: "endpoint=https://<dev-acs-resource>.communication.azure.com/;accesskey=<dev-acs-access-key>"
  otel-otlp-endpoint: "http://otel-collector.monitoring.svc.cluster.local:4317"
  oauth2-issuer: "https://login.microsoftonline.com/<dev-tenant-id>/v2.0"
  oauth2-audience: "api://<dev-app-id-uri>"
  oauth2-jwk-set-uri: "https://login.microsoftonline.com/<dev-tenant-id>/discovery/v2.0/keys"
  azure-sql-jdbc-url: "jdbc:sqlserver://<dev-sql-server>.database.windows.net:1433;database=<dev-shared-db>;encrypt=true;hostNameInCertificate=*.database.windows.net;loginTimeout=30;"
  azure-sql-username: "<dev-sql-user>"
  azure-sql-password: "<dev-sql-password-or-token>"
  azure-managed-identity-client-id: "<dev-user-assigned-managed-identity-client-id>"
