apiVersion: v1
kind: Secret
metadata:
  name: platform-secrets
  namespace: healthcare-dev
type: Opaque
stringData:
  servicebus-namespace: "sb-hpe-devx-feea64.servicebus.windows.net"
  eventhub-namespace: "eh-hpe-devx-feea64.servicebus.windows.net"
  key-vault-url: "https://kv-hpe-devx-feea64.vault.azure.net/"
  fhir-integration-base-url: "https://hpe-devx-fhir.azurehealthcareapis.com"
  service-bus-integration-base-url: "https://svc-event-messaging.healthcare-dev.svc.cluster.local"
  otel-otlp-endpoint: "http://otel-collector.monitoring.svc.cluster.local:4317"
  oauth2-issuer: "https://login.microsoftonline.com/65087c47-0017-4258-8086-72832006d566/v2.0"
  oauth2-audience: "04c9437e-5974-42ce-896f-0b2dbfd5aa38"
  oauth2-jwk-set-uri: "https://login.microsoftonline.com/65087c47-0017-4258-8086-72832006d566/discovery/v2.0/keys"
  azure-sql-jdbc-url: "jdbc:sqlserver://sqlhpedevxfeea64.database.windows.net:1433;database=healthcare-dev;encrypt=true;hostNameInCertificate=*.database.windows.net;loginTimeout=30;"
  azure-sql-username: "hpesqladmin"
  azure-sql-password: "HpeDevxPass1234A"
  azure-managed-identity-client-id: "c0e0ecfd-3d88-432f-9329-443d124ffae8"